from .orders import orders_bp
from .auth import auth_bp
from .payments import payments_bp
from .chat import chat_bp
from .stats import stats_bp
from .couriers import couriers_bp
from .zones import zones_bp
from .settings import settings_bp
from .reports import reports_bp
