"""Init

Revision ID: 350b3de640fc
Revises: 
Create Date: 2026-01-29 01:53:10.433416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350b3de640fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pickup_address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('courier_id', sa.INTEGER(), nullable=True),
    sa.Column('courier_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
