"""Add courier table

Revision ID: 5e3e7216069d
Revises: fa2d8e82e9ab
Create Date: 2026-02-14 14:02:40.669440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '5e3e7216069d'
down_revision: Union[str, None] = 'fa2d8e82e9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('MOTORCYCLE', 'SCOOTER', 'CAR', 'BICYCLE', 'VAN', name='vehicletype'), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_couriers_location', 'couriers', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_index(op.f('ix_couriers_user_id'), 'couriers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_couriers_user_id'), table_name='couriers')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_index('idx_couriers_location', table_name='couriers', postgresql_using='gist')
    op.drop_table('couriers')
    # ### end Alembic commands ###
