"""add_tzir_academy_models

Revision ID: 771fc29afc7b
Revises: 9eb0c06c006c
Create Date: 2026-02-21 17:08:19.810905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771fc29afc7b'
down_revision = '9eb0c06c006c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('fcm_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('fcm_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
