"""Init PostGIS

Revision ID: 9eb0c06c006c
Revises: 
Create Date: 2026-01-29 12:13:21.531616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb0c06c006c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        batch_op.create_index('idx_addresses_geom', ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        batch_op.create_index('idx_couriers_location_geom', ['location_geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_payload', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_session_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_hash', sa.String(length=128), nullable=True))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rated_by', sa.Enum('customer', 'courier', 'system', name='rating_source'), nullable=False))

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        batch_op.alter_column('polygon_coordinates',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index('idx_zones_area_geom', ['area_geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index('idx_zones_area_geom', postgresql_using='gist')
        batch_op.alter_column('polygon_coordinates',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('area_geom')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('rated_by')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('key_hash')
        batch_op.drop_column('encrypted_session_key')
        batch_op.drop_column('encrypted_payload')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('total_orders')
        batch_op.drop_column('rating')

    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_index('idx_couriers_location_geom', postgresql_using='gist')
        batch_op.drop_column('location_geom')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_addresses_geom', postgresql_using='gist')
        batch_op.drop_column('geom')

    # ### end Alembic commands ###
