"""Added email and additional_phones to Customer

Revision ID: bd88f9ba02d9
Revises: 822b092fab26
Create Date: 2026-03-11 16:55:58.241836

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bd88f9ba02d9'
down_revision = '822b092fab26'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.alter_column('employment_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('freelance', 'employee', name='employment_types'),
               existing_nullable=True,
               existing_server_default=sa.text("'freelance'"))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_phones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('customer_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('private', 'business', name='customer_type_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'business'"))
        batch_op.alter_column('tax_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('vat_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('exempt', 'authorized_dealer', 'company', 'standard', name='vat_statuses'),
               existing_nullable=True,
               existing_server_default=sa.text("'standard'"))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('base_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('tax_invoice_receipt', 'receipt', 'tax_invoice', 'transaction_invoice', 'credit_note', name='invoice_document_types'),
               nullable=False,
               existing_server_default=sa.text("'tax_invoice_receipt'"))

    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('stop_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pickup', 'delivery', 'waypoint', name='stop_type'),
               existing_nullable=True,
               existing_server_default=sa.text("'delivery'"))

    with op.batch_alter_table('saved_routes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('draft', 'published', 'assigned', 'completed', name='route_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('saved_routes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'published', 'assigned', 'completed', name='route_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.alter_column('stop_type',
               existing_type=sa.Enum('pickup', 'delivery', 'waypoint', name='stop_type'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'delivery'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.Enum('tax_invoice_receipt', 'receipt', 'tax_invoice', 'transaction_invoice', 'credit_note', name='invoice_document_types'),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'tax_invoice_receipt'"))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('base_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('vat_status',
               existing_type=sa.Enum('exempt', 'authorized_dealer', 'company', 'standard', name='vat_statuses'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'standard'"))
        batch_op.alter_column('tax_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('customer_type',
               existing_type=sa.Enum('private', 'business', name='customer_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'business'"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('email')
        batch_op.drop_column('additional_phones')

    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.alter_column('employment_type',
               existing_type=sa.Enum('freelance', 'employee', name='employment_types'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'freelance'"))

    # ### end Alembic commands ###